### ISSUE TITLE
WalletConnect sign QR from Terminal

### ISSUE THREAD

**Issue by insipx** [WalletConnect/WalletConnectRust#60]
Hello!

I've been building a toy terminal chat app with rust & ratatui, and want to incorporate a way for a user to get into the app via their Ethereum Wallet. I found [walletconnect](https://crates.io/crates/walletconnect) crate, which allows signing a QR code walletconnect-style to get a wallet instance. However, this crate is a couple years old and has not been updated. I believe its still on an old version of the walletconnect protocol.

I was wondering if this library is mature enough, or will be mature enough (or if it is even possible/a goal) to do what the walletconnect crate does. If not, what has to be done to get it there? 

I saw the sign example in the PRs, but that requires interacting with a webui(terminal only!). Is it possible to create an example that uses only the terminal?

**Comment by chris13524** [comment]
It doesn't appear to me that #48 requires a web UI. It happens to demonstrate usage with react-app as the other side of the sign session, but the wallet-side is implemented as a headless app. There should be no problem in building either side of the session without a web UI.

That being said, the implementation there is immature and may or may not work for you. You are welcome to contribute to make it functional for your use case, but for now, it is not a priority of our Rust team to support a Rust-based Sign API implementation.
